---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: shipwright-triggers
rules:
- apiGroups:
  - shipwright.io
  resources:
  - buildruns
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - shipwright.io
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - customruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - customruns/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - customruns/status
  verbs:
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
